name: Deploy Content to siemstress [6cb868e4-e4dc-4dcc-96bb-e9a8f22ba7c8]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-6cb868e4-e4dc-4dcc-96bb-e9a8f22ba7c8.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-6cb868e4-e4dc-4dcc-96bb-e9a8f22ba7c8.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'cloud-shell-storage-southcentralus'
      workspaceName: 'siemstress'
      workspaceId: '5e1e48d7-fef6-4e98-a768-0f53f6c40dc1'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook'
      branch: 'main'
      sourceControlId: '6cb868e4-e4dc-4dcc-96bb-e9a8f22ba7c8'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_6cb868e4e4dc4dcc96bbe9a8f22ba7c8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-6cb868e4-e4dc-4dcc-96bb-e9a8f22ba7c8.ps1